#端口号默认为8888
server:
  port: 9090
#Spring Profiles
#datasource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/bbt?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
      username: root
      password: 7887227
      #初始化大小，最大，最小
      initial-size: 5
      min-idle: 5
      max-active: 10
      #配置获取连接等待超时的时间
      max-wait: 60000

      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query-timeout: 60000
      validation-query: SELECT 1 FROM DUAL
      #打开PSCache,并且制定每个链接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  #邮件
  mail:
    host: smtp.qq.com
    username: 1145054472@qq.com
    password: ptdzuiymqlyrffga
    default-encoding: UTF-8
  #文件上传
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
#mybatis路径
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
#fastdfs
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  resHost: 47.107.249.89
  storagePort: 8888
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 47.107.249.89:22122
#日志
logging:
  level:
    root: warn
    com.scutj2ee.bookstore: DEBUG


